---
title: "10/23 In-class practice"
author: "Boxuan Li"
date: "10/23/2017"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)
```

# locate the tables
```{r}
drug_use_xml %>%
  html_nodes(css = "table")
```

# extract the table of interest
```{R}
table_marj = (drug_use_xml %>% html_nodes(css = "table"))[[1]] %>%
  html_table()
names(table_marj)

table_marj <- table_marj[-1,] %>%
  as_tibble()
```

# exercise
```{r}
url2 <- "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"

cost_living_xml <- read_html(url2)

html_nodes(cost_living_xml, css = "table")

nyc_cost_table = (cost_living_xml %>% html_nodes(css = "table"))[[2]] %>%
  html_table(header = T)
```

# HP_SS cast
```{r}
url3 <- "http://www.imdb.com/title/tt0241527/"

hpss_xml <- read_html(url3)

hpss_cast <- hpss_xml %>%
  html_nodes(css = ".itemprop .itemprop") %>%
  html_text()
```

# Toothbrush review
```{r}
url4 <- "https://www.amazon.com/Philips-Sonicare-rechargeable-toothbrush-HX6211/product-reviews/B00YAR7ZFM/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&reviewerType=all_reviews&sortBy=recent&pageNumber=1"

toothbrush_xml <- read_html(url4)

toothbrush_review <- toothbrush_xml %>%
  html_nodes(css = ".a-color-base") %>%
  html_text()
toothbrush_review

toothbrush_REstar <- toothbrush_xml %>%
  html_nodes(css = "#cm_cr-review_list .review-rating") %>%
  html_text()
toothbrush_REstar
```


